name: MCDiscordRegions
description: WorldGuard Discord channel integrations.
version: 0.1
api-version: 1.15
main: nl.codestix.mcdiscordregions.MCDiscordRegionsPlugin
author: Stijn Rogiest
depend: [WorldGuard]
commands:
 dregion:
   aliases: [drg]
   description: Configure the MCDiscordRegions plugin.
   usage: /dregion [info | whitelist [on|off] | entry <channelName...> | category <categoryName...> | kickOnDiscordLeave [on|off] [kickMessage...] | deletecategory [confirm] | save | limit <maxUsers> <channelName...>]