name: MCDiscordRegions
description: WorldGuard Discord channel integrations.
version: 1.15.2
api-version: 1.15
main: nl.codestix.mcdiscordregions.MCDiscordRegionsPlugin
author: Stijn Rogiest
depend: [WorldGuard, WorldGuardEvents]
commands:
 drg:
   description: Configure the MCDiscordRegions plugin.
   usage: /drg [server <serverId> | message <message> | info | list | entry <channelName> | category <categoryName>]