name: MCDiscordRegions
description: WorldGuard Discord channel integrations.
version: 0.0.1
api-version: 1.15.2
main: nl.codestix.mcdiscordregions.MCDiscordRegionsPlugin
author: Stijn Rogiest
depend: [WorldGuard, WorldGuardEvents]
commands:
 drg:
   description: Configure the MCDiscordRegions plugin.
   usage: /drg [info | entry <channelName> | global <channelName> | category <categoryName> | server <serverId>]